Set yarn to version berry
themoment-team/the_moment_front pull request #180
Opened 2021-09-23 04:57 UTC by sunwoo0706

## 개요

프로젝트 규모가 커짐에 따라 효율적인 종속성 관리 툴이 필요하여 `yarn berry` 설정을 하였습니다.

## 작업사항

### 기본 설정 관련

[`yarnpkg.com`](https://yarnpkg.com/)을 보고 플러그 앤 플레이 방식으로 `yarn berry` 설정을 하였고 그 이후 발생된 이슈들을 처리했습니다. 마이그레이션시 참고한 자료입니다. [📖](https://yarnpkg.com/getting-started/migration) <

`.pnp.cjs` 에 플러그 앤 플레이가 디폴트로 설정되어 있기는 하지만 명시해주면 좋을것 같아 아래 코드를 삽입했습니다.
```cjs
nodeLinker: "pnp"
```
그리고 플러그 앤 플레이 방식으로 변경됨에 따라 기존의 `node-modules` (gitignore당해서 github에는 존재하지 않음)와 `package-lock.json`을 제거했습니다.

그리고 `package.json`에서는 `eslint` 설정을 불러올 수 없기에 `.eslintrc.json`에 다음과 같은 코드를 옮겼습니다.

```json
{
    "extends": [
        "react-app",
        "react-app/jest"
    ]
}
```

### yarn script 관련

> `yarn start` 실행시  발생하는 에러들이었습니다.

1. **command not found**
`react-script start` 앞에 `export 8080 ...` 코드때문에 실행이 되지 않았습니다.
2. **react-script 안됨**
`yarn add eslint-config-react-app` 을 입력하여 해결했습니다. [관련 자료](https://github.com/facebook/create-react-app/issues/10002)
3. **react-router not declare**
`yarn add react-router eslint-config-react-app` 을 입력하여 해결하였습니다. [관련 자료](https://github.com/facebook/create-react-app/issues/9446)
4. **styled-component 로 인해 실행 안됨**
`yarn add react-is`를 입력하여 해결했습니다. [관련 자료](https://github.com/yarnpkg/berry/issues/966)

### type-script 관련

> `type-script` 적용하기 위해서 `yarn dlx @yarnpkg/sdks vscode` 를 입력하여 적용시켰습니다.

아직은 머지하지 말아주세요

2021-09-23 05:51 UTC, iseolin76 requested changes
수고하셨습니다

2021-09-23 05:51 UTC, iseolin76 commented on .eslintrc.json
> +      "react-app/jest"
우리 jest 쓰나요?

2021-09-23 05:52 UTC, sunwoo0706 commented on .eslintrc.json
> +      "react-app/jest"
`cra` 기본 설정입니다.

2021-09-23 05:52 UTC, iseolin76 commented on .eslintrc.json
> +      "react-app/jest"
사용하지 않으면 제거하는 게 어떨까 합니다

2021-09-23 05:53 UTC, sunwoo0706 commented on .eslintrc.json
> +      "react-app/jest"
정확하게 알지 않는 기본 설정은 건드리지 않는게 좋을것 같아요

2021-09-23 05:54 UTC, sunwoo0706 commented on .eslintrc.json
> +      "react-app/jest"
나중에 무언가를 설정할때 우리가 `cra` 튜토리얼을 따라서 하다가 중간에 관련에러가 발생하면 고치기가 매우 어려워집니다.

2021-09-23 05:55 UTC, sunwoo0706 commented on .eslintrc.json
> +      "react-app/jest"
1. command not found
`react-script start` 앞에 `export 8080 ...` 코드때문에 실행이 되지 않았습니다.
ㄴ 이것과 같이 말이죠

2021-09-23 14:33 UTC, iseolin76 approved these changes
LGTM

2021-09-28 05:21 UTC, sunwoo0706 commented
이제 리뷰해주시면 됩니다 !!
@iseolin76 @songsihyeon @ImChangGyu

2021-09-28 05:41 UTC, iseolin76 approved these changes

2021-09-28 07:37 UTC, sunwoo0706 commented
conflict로 인하여 develop에 있는 코드로 세팅하도록 하겠습니다.

2021-09-28 07:37 UTC, closed without merging