Update Style Legacy 처리 및 재구조
themoment-team/the_moment_front pull request #182
Opened 2021-09-26 23:15 UTC by ImChangGyu

## 개요
header legacy 청산

## 작업사항
로직 재 배치
Position 처리

## 참조
제가 생각하기에 반응형에 맞는 스타일링이 뭔지 잘 모르겠습니다 많은 리뷰 부탁드립니다.

2021-09-26 23:23 UTC, iseolin76 approved these changes
LGTM

2021-09-27 05:00 UTC, sunwoo0706 commented
pr 콘텐츠 내부 코드 블럭 부분에 `ts` 추가해주시면 더 잘 보일것 같아요.

> 예시 :
```ts
const hello: string = "sunwoo"
```

2021-09-27 05:06 UTC, sunwoo0706 requested changes
스타일 컴포넌트 중첩 부분 별도의 컴포넌트로 분리 요구

2021-09-27 05:06 UTC, sunwoo0706 commented on src/Components/Common/Header/styled.tsx
> +  }
중첩이 3중으로 되어 있어서 보기가 어렵네요 이 부분도 컴포넌트로 분리해주시면 더 좋을것 같습니다.

2021-09-27 05:20 UTC, ImChangGyu commented on src/Components/Common/Header/styled.tsx
> +  }
넵 알겠습니다.

2021-09-27 05:24 UTC, sunwoo0706 approved these changes
LGTM

2021-09-27 05:32 UTC, merged