Setting Prettier
themoment-team/the_moment_front pull request #186
Opened 2021-09-28 10:47 UTC by ImChangGyu

## 개요

협업규칙에 맞춰 코드 스타일을 맞추기 위해 설정

## 작업사항

/.prettierrc
```json
{
  "singleQuote": false,
  "semi": true,
  "tabWidth": 2
}
```
doubleQuote 사용, 세미콜론 사용, tab길이는 2

/.prettierignore
```json
# 디렉토리
/.github
/.vscode
/.yarn
/node_modules

# Plug N Play
*/.pnp.cjs
```
각 yarn barry로 설정된 directory들을 prettier가 적용되지 않게 하기 위해 ignore해줌
## 참조

ignore가 잘못되었거나 prettier가 잘못 설정된 경우 review해주세요

2021-09-28 11:09 UTC, iseolin76 approved these changes
LGTM

2021-09-28 11:10 UTC, iseolin76 commented
<img width="896" alt="스크린샷 2021-09-28 오후 8 10 06" src="https://user-images.githubusercontent.com/65021545/135076073-1b93b00a-bbc2-4622-bc33-5b8f2a7f1607.png">
근데 이거 맞아요?

2021-09-28 11:14 UTC, sunwoo0706 commented
엥 `develop`인데 `netlify`가 왜 뜨지

2021-09-28 11:21 UTC, ImChangGyu reviewed
이게 제가 처음에 잘못 main으로 해서 그렇습니다

2021-09-28 12:13 UTC, sunwoo0706 requested changes

2021-09-28 12:14 UTC, ImChangGyu commented on .prettierrc
> +}
넵 prettierignore를 제외한 모든 파일에 적용이 됩니다.

2021-09-28 23:23 UTC, sunwoo0706 commented on .prettierignore
> +*/.pnp.cjs
`prettierignore` 파일에
```
build
coverage
```
추가해주세요

2021-09-28 23:25 UTC, sunwoo0706 commented
그리고 [다음 자료](https://prettier.io/docs/en/install.html) 참고하시어 이그노어 시킨 파일 제외한 모든 파일에 적용시켜주세요

2021-09-29 01:30 UTC, sunwoo0706 commented on .prettierrc.json
> +{}
@ImChangGyu 이 파일은 무엇인가요?

2021-09-29 02:25 UTC, ImChangGyu commented on .prettierrc.json
> +{}
위 자료에서 필요하다고 하여 만들었는데 필요 없는 파일이라 지운다는걸 실수로 지우지 않고 커밋한거 같습니다

2021-09-29 02:31 UTC, sunwoo0706 commented on .prettierrc.json
> +{}
넵 삭제 부탁드립니다. @ImChangGyu

2021-09-29 02:34 UTC, sunwoo0706 approved these changes

2021-09-29 02:46 UTC, merged